export const ANIMALS = [
  // --- KEDİLER ---
  {
    id: "kedi-1",
    name: "Pamuk",
    breed: "British Longhair",
    age: "2 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/british_longhair_1.jpg",
  },
  {
    id: "kedi-2",
    name: "Mochi",
    breed: "British Longhair",
    age: "1 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/british_longhair_2.jpg",
  },
  {
    id: "kedi-3",
    name: "Simba",
    breed: "British Shorthair",
    age: "3 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/british_shorthair_1.jpg",
  },
  {
    id: "kedi-4",
    name: "Duman",
    breed: "British Shorthair",
    age: "2 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/british_shorthair_2.jpg",
  },
  {
    id: "kedi-5",
    name: "Gece",
    breed: "Norveç Orman Kedisi",
    age: "4 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/norvec_orman_kedisi_1.jpg",
  },
  {
    id: "kedi-6",
    name: "Mila",
    breed: "Norveç Orman Kedisi",
    age: "1.5 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/norvec_orman_kedisi_2.jpg",
  },
  {
    id: "kedi-7",
    name: "Sarman",
    breed: "Sarman",
    age: "2 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/sarman_1.jpg",
  },
  {
    id: "kedi-8",
    name: "Zeytin",
    breed: "Sarman",
    age: "1 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/sarman_2.jpg",
  },
  {
    id: "kedi-9",
    name: "Pati",
    breed: "Tekir",
    age: "3 Yaşında",
    category: "kedi",
    image: "/images/animals/kedi/tekir_kedi_1.jpg",
  },
  {
    id: "kedi-10",
    name: "Gofret",
    breed: "Tekir",
    age: "6 Aylık",
    category: "kedi",
    image: "/images/animals/kedi/tekir_kedi_2.jpg",
  },

  // --- KÖPEKLER ---
  {
    id: "kopek-1",
    name: "Baron",
    breed: "Alman Kurdu",
    age: "3 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/alman_kurdu_1.jpg",
  },
  {
    id: "kopek-2",
    name: "Max",
    breed: "Alman Kurdu",
    age: "2 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/alman_kurdu_2.jpg",
  },
  {
    id: "kopek-3",
    name: "Bella",
    breed: "Border Collie",
    age: "1 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/border_collie_1.jpg",
  },
  {
    id: "kopek-4",
    name: "Çakıl",
    breed: "Border Collie",
    age: "4 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/border_collie_2.jpg",
  },
  {
    id: "kopek-5",
    name: "Fırtına",
    breed: "French Bulldog",
    age: "2 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/french_bulldog_1.jpg",
  },
  {
    id: "kopek-6",
    name: "Maya",
    breed: "French Bulldog",
    age: "1.5 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/french_bulldog_2.jpg",
  },
  {
    id: "kopek-7",
    name: "Badi",
    breed: "Golden Retriever",
    age: "3 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/golden_kopek_1.jpg",
  },
  {
    id: "kopek-8",
    name: "Zorro",
    breed: "Golden Retriever",
    age: "1 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/golden_kopek_2.jpg",
  },
  {
    id: "kopek-9",
    name: "Karabaş",
    breed: "Golden Retriever",
    age: "5 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/golden_kopek_3.jpg",
  },
  {
    id: "kopek-10",
    name: "Hera",
    breed: "Pomeranian",
    age: "2 Yaşında",
    category: "kopek",
    image: "/images/animals/kopek/pomerian_1.jpg",
  },

  // --- KUŞLAR ---
  {
    id: "kus-1",
    name: "Maviş",
    breed: "Gri Papağan",
    age: "2 Yaşında",
    category: "kus",
    image: "/images/animals/kus/gri_papagan_1.jpg",
  },
  {
    id: "kus-2",
    name: "Limon",
    breed: "Gri Papağan",
    age: "1 Yaşında",
    category: "kus",
    image: "/images/animals/kus/gri_papagan_2.jpg",
  },
  {
    id: "kus-3",
    name: "Fıstık",
    breed: "Hint Bülbülü",
    age: "4 Aylık",
    category: "kus",
    image: "/images/animals/kus/hint_bulbulu_1.jpg",
  },
  {
    id: "kus-4",
    name: "Bulut",
    breed: "Hint Bülbülü",
    age: "6 Aylık",
    category: "kus",
    image: "/images/animals/kus/hınt_bulbulu_2.jpg",
  },
  {
    id: "kus-5",
    name: "Güneş",
    breed: "Kanarya",
    age: "1 Yaşında",
    category: "kus",
    image: "/images/animals/kus/kanarya_1.jpg",
  },
  {
    id: "kus-6",
    name: "Cici",
    breed: "Kanarya",
    age: "2 Yaşında",
    category: "kus",
    image: "/images/animals/kus/kanarya_2.jpg",
  },
  {
    id: "kus-7",
    name: "Şakir",
    breed: "Muhabbet Kuşu",
    age: "8 Aylık",
    category: "kus",
    image: "/images/animals/kus/muhabbet_kusu_1.jpg",
  },
  {
    id: "kus-8",
    name: "Boncuk",
    breed: "Muhabbet Kuşu",
    age: "1 Yaşında",
    category: "kus",
    image: "/images/animals/kus/muhabbet_kusu_2.jpg",
  },
  {
    id: "kus-9",
    name: "Hulusi",
    breed: "Sultan Papağanı",
    age: "1.5 Yaşında",
    category: "kus",
    image: "/images/animals/kus/sultan_papaganı_2.jpg",
  },
  {
    id: "kus-10",
    name: "Pırtık",
    breed: "Sultan Papağanı",
    age: "1 Yaşında",
    category: "kus",
    image: "/images/animals/kus/sultan_papaganı_3.jpg",
  },

  // --- EGZOTİKLER ---
  {
    id: "egz-1",
    name: "Rango",
    breed: "Bukalemun",
    age: "1 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/bukalemun_1.jpg",
  },
  {
    id: "egz-2",
    name: "Echo",
    breed: "Bukalemun",
    age: "2 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/bukalemun_2.jpg",
  },
  {
    id: "egz-3",
    name: "Igu",
    breed: "İguana",
    age: "3 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/iguana_1.jpg",
  },
  {
    id: "egz-4",
    name: "Rex",
    breed: "İguana",
    age: "4 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/iguana_2.jpg",
  },
  {
    id: "egz-5",
    name: "Spike",
    breed: "İguana",
    age: "2 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/iguana_3.jpg",
  },
  {
    id: "egz-6",
    name: "Lizard",
    breed: "İguana",
    age: "5 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/iguana_4.jpg",
  },
  {
    id: "egz-7",
    name: "Tıstıs",
    breed: "Mısır Yılanı",
    age: "2 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/mısır_yılanı_1.jpg",
  },
  {
    id: "egz-8",
    name: "Spider",
    breed: "Tarantula",
    age: "1 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/tarantula_1.jpg",
  },
  {
    id: "egz-9",
    name: "Gonzo",
    breed: "Tarantula",
    age: "2 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/tarantula_2.jpg",
  },
  {
    id: "egz-10",
    name: "Ninja",
    breed: "Tarantula",
    age: "1.5 Yaşında",
    category: "egzotik",
    image: "/images/animals/egzotik/tarantula_3.jpg",
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    category: "Kedi",
    title: "Kediler Neden Mırıldanır?",
    description:
      "Mırıldanma sadece mutluluk belirtisi değildir; kedilerin kendilerini iyileştirme yöntemi de olabilir.",
    date: "13 Mayıs 2026",
    image: "/images/blog/kedi-mirildanma.jpg",
    content:
      "Kedilerin mırıldanması genellikle bir memnuniyet ifadesi olarak bilinse de, aslında çok daha karmaşık bir iletişim aracıdır. Yapılan araştırmalar, kedilerin mırıldanma frekansının (25-150 Hertz arası) kemik yoğunluğunu artırabildiğini ve doku onarımını hızlandırdığını göstermiştir. Yani kediniz sadece mutlu olduğu için değil, aynı zamanda kendini iyileştirmek veya stresli bir durumla başa çıkmak için de mırıldanabilir.",
  },
  {
    id: 2,
    category: "Köpek",
    title: "Köpeklerde Temel İtaat Eğitimi",
    description:
      "Yeni sahiplendiğiniz dostunuzla bağınızı güçlendirecek ilk 5 komut ve eğitim ipuçları.",
    date: "12 Mayıs 2026",
    image: "/images/blog/kopek-egitim.jpg",
    content:
      "Yeni bir köpekle yaşamaya başladığınızda ilk öğretmeniz gereken 'otur, bekle, gel' gibi komutlar sadece birer gösteri değil, köpeğinizin güvenliği için hayati önem taşır. Eğitim sırasında ceza yerine her zaman ödül mamasını ve övgüyü (pozitif pekiştirme) kullanmalısınız. Günlük 15 dakikalık kısa seanslar, köpeğinizin hem zihinsel olarak yorulmasını sağlar hem de aranızdaki güven bağını en üst seviyeye taşır.",
  },
  {
    id: 3,
    category: "Kuş",
    title: "Muhabbet Kuşları İçin Sağlıklı Beslenme",
    description:
      "Sadece yem yeterli mi? Kuşunuzun tüylerinin parlaması için taze meyve ve sebze takviyeleri.",
    date: "11 Mayıs 2026",
    image: "/images/blog/kus-beslenme.jpg",
    content:
      "Çoğu kuş sahibi sadece paketlenmiş yemlerin yeterli olduğunu düşünür, ancak bu büyük bir yanılgıdır. Kuşunuzun sağlıklı bir tüy yapısına sahip olması için diyetinin %20'si taze sebze ve meyvelerden oluşmalıdır. Özellikle brokoli, rendelenmiş havuç ve elma (çekirdeksiz) kuşlar için harika vitamin kaynaklarıdır. Ayrıca gaga sağlığı için kafeste her zaman bir mürekkep balığı kemiği bulunmalıdır.",
  },
  {
    id: 4,
    category: "Egzotik",
    title: "Bukalemun Bakımı: Yeni Başlayanlar İçin",
    description:
      "Renk değiştiren bu gizemli dostlarımızın teraryum sıcaklığı ve nem dengesi nasıl olmalı?",
    date: "10 Mayıs 2026",
    image: "/images/blog/egzotik-bukalemun.jpg",
    content:
      "Bukalemunlar evde bakımı en zor ama en ödüllendirici egzotik canlılardan biridir. Onlar için en kritik nokta su içme alışkanlıklarıdır; bukalemunlar kaptan su içmezler, yapraklardan süzülen damlaları yalarlar. Bu yüzden teraryumun günde iki kez nemlendirilmesi veya bir damlama sistemi kurulması şarttır. Ayrıca UV ışığı, kalsiyum sentezlemeleri için hayati bir zorunluluktur.",
  },
  {
    id: 5,
    category: "Kedi",
    title: "Ev Yapımı Kedi Oyuncakları",
    description:
      "Karton kutulardan ve eski çoraplardan kedinizi saatlerce eğlendirecek yaratıcı fikirler.",
    date: "09 Mayıs 2026",
    image: "/images/blog/kedi-oyuncak.jpg",
    content:
      "Kediler için en pahalı oyuncak her zaman en iyisi değildir. Boş bir ayakkabı kutusunun içine açacağınız delikler, kediniz için saatlerce sürecek bir 'av' oyununa dönüşebilir. Eski bir çorabın içine kurutulmuş kedi nanesi (catnip) koyup düğümleyerek ona harika bir kafa dağıtıcı yapabilirsiniz. Önemli olan, oyuncağın kedinizin doğal avlanma içgüdüsünü tetiklemesidir.",
  },
  {
    id: 6,
    category: "Köpek",
    title: "Köpeklerde Tüy Dökülmesiyle Baş Etme",
    description:
      "Mevsimsel tüy dökümünü azaltmak için doğru tarama teknikleri ve beslenme tavsiyeleri.",
    date: "08 Mayıs 2026",
    image: "/images/blog/kopek-tuy-bakimi.jpg",
    content:
      "Mevsim geçişlerinde artan tüy dökülmesiyle baş etmenin sırrı düzenli fırçalamadır. Haftada en az 3 kez yapılacak tarama işlemi, dökülen tüylerin evinize yayılmadan toplanmasını sağlar. Ayrıca omega-3 ve omega-6 bakımından zengin bir beslenme düzeni, deri sağlığını koruyarak dökülmeyi minimize eder. Eğer tüy dökülmesi aşırıysa ve deri bölgelerinde açılmalar varsa mutlaka bir veteriner hekime danışılmalıdır.",
  },
  {
    id: 7,
    category: "Kuş",
    title: "Sultan Papağanları Neden Islık Çalar?",
    description:
      "Bu zeki kuşların çıkardığı seslerin anlamları ve size anlatmaya çalıştıkları duygular.",
    date: "07 Mayıs 2026",
    image: "/images/blog/kus-papagan.jpg",
    content:
      "Sultan papağanları sosyal canlılardır ve ıslık çalarak sizinle iletişim kurarlar. Eğer papağanınız sürekli aynı melodiyi çalıyorsa, bu onun çok mutlu ve kendini güvende hissettiği anlamına gelir. Dişi sultan papağanları genellikle daha sessizken, erkekler karmaşık ıslıklar çalmaya ve konuşmaya daha meyillidir. Onlara yeni melodiler öğretmek için gün içinde aynı ritmi tekrarlamanız yeterlidir.",
  },
  {
    id: 8,
    category: "Egzotik",
    title: "Kaplumbağalar Hakkında Az Bilinenler",
    description:
      "Evcil kaplumbağaların ömürleri, kış uykusu süreçleri ve doğru akvaryum kurulumu.",
    date: "06 Mayıs 2026",
    image: "/images/blog/egzotik-kaplumbaga.jpg",
    content:
      "Evcil kaplumbağalar genellikle 'bakımı kolay' olarak pazarlansa da aslında 40-50 yıl yaşayabilen uzun ömürlü arkadaşlardır. En sık yapılan hata, onları sadece küçük kaplarda beslemektir. Kaplumbağaların yüzeceği geniş bir su alanı ve üzerine çıkıp kuruyabilecekleri, bir ısı lambasıyla aydınlatılmış 'güneşlenme alanı'na ihtiyaçları vardır. Su temizliği için güçlü bir filtre sistemi olmazsa olmazdır.",
  },
  {
    id: 9,
    category: "Kedi",
    title: "Yaşlı Kedilerde Sağlık Kontrolü",
    description:
      "7 yaş üstü kedilerde dikkat edilmesi gereken belirtiler ve düzenli veteriner kontrolünün önemi.",
    date: "05 Mayıs 2026",
    image: "/images/blog/kedi-saglik.jpg",
    content:
      "Kediniz 7 yaşını geçtiğinde artık 'olgunluk' dönemine girmiş sayılır. Bu dönemde böbrek sağlığına ve diş eti problemlerine karşı ekstra dikkatli olunmalıdır. Yaşlı kediler daha az hareket ettiği için kilo almaya meyillidirler, bu yüzden protein oranı dengeli 'senior' mamalara geçiş yapılmalıdır. Yılda iki kez yapılacak veteriner kontrolleri, olası hastalıkların erken teşhisi için kritiktir.",
  },
  {
    id: 10,
    category: "Köpek",
    title: "Sokaktaki Dostlarımıza Nasıl Yardım Ederiz?",
    description:
      "Mahallenizdeki sahipsiz hayvanlar için su kabı, mama ve barınak yapımı rehberi.",
    date: "04 Mayıs 2026",
    image: "/images/blog/sokak-hayvanlari.jpg",
    content:
      "Mahallenizdeki sahipsiz dostlarımız için yapabileceğiniz en basit ama etkili şey kapınızın önüne bir kap temiz su koymaktır. Kışın strafor kutulardan yapacağınız rüzgar geçirmeyen barınaklar hayat kurtarıcı olabilir. Ayrıca bulunduğunuz bölgedeki belediye veya derneklerle iş birliği yaparak kısırlaştırma süreçlerine destek olmak, sokaktaki nüfusun kontrol altına alınması için en kalıcı çözümdür.",
  },
];
